### ISSUE TITLE
training on custom dataset

### ISSUE THREAD

**Issue by abdo-ameen** [aclex/detection-experiments#2]
how can I train this model on my own custom dataset?

**Comment by aclex** [comment]
Currently Pascal VOC and COCO dataset formats are supported. You can dump your custom dataset into either of these two formats (e.g. in [cvat](https://cvat.org/)) and just point the `train.py` to it, specifying format with `--dataset-style` parameter, path to it with `--dataset` parameter and image set for VOC or annotation filename for COCO for training and validation stages with `--train-image-set` and `--val-image-set` keys (they are set with `train` and `val` by default, correspondingly).

**Comment by abdo-ameen** [comment]
thank you so much
