### ISSUE TITLE
raise ValueError("bbox_params must be specified for bbox transformations")

### ISSUE THREAD

**Issue by xings-sdnu** [aclex/detection-experiments#4]
When train on a custom dataset, I run it by this command: python train.py --dataset-style=coco --dataset peach --train-image-set=train --val-image-set=val --net-config preset/gn-0.25-bifpn-fcos.json --scheduler cosine-wr --lr 0.01 --t0 5 --num-epochs 5,but I got this error, how can I solve it? Thank you!

**Comment by chenyonx** [comment]
hey， brother,how do you sovle it?
